DROP TABLE IF EXISTS statistics;

CREATE TABLE IF NOT EXISTS statistics
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     VARCHAR(255)                            NOT NULL,
    uri     VARCHAR(255)                            NOT NULL,
    ip      VARCHAR(39)                             NOT NULL,
    created TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_statistics PRIMARY KEY (id)
--     CONSTRAINT uq_statistics UNIQUE (app, uri, ip, created)
);